import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f6f8f6",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#0d1b0d",
  },
  content: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  title: {
    fontSize: 26,
    fontWeight: "bold",
    color: "#0d1b0d",
    marginBottom: 8,
  },
  description: {
    fontSize: 14,
    color: "#3a4a3a",
    marginBottom: 12,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 8,
  },
  input: {
    flex: 1,
    backgroundColor: "rgba(19, 236, 19, 0.2)",
    borderRadius: 12,
    paddingHorizontal: 16,
    height: 56,
    fontSize: 16,
    color: "#0d1b0d",
  },
  deleteButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(19, 236, 19, 0.2)",
    alignItems: "center",
    justifyContent: "center",
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderStyle: "dashed",
    borderColor: "rgba(19, 236, 19, 0.5)",
    borderRadius: 12,
    paddingVertical: 14,
    marginTop: 10,
  },
  addButtonText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#13ec13",
    marginLeft: 6,
  },
  footer: {
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  stylishButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#13ec13",
    borderRadius: 30,
    paddingVertical: 16,
    shadowColor: "#0a7f0a",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 6,
    gap: 8,
  },
  submitText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
    marginRight: 8,
  },
});
